/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.taotao.manager.pojo;

import java.sql.Date;

/**
 * <p>实体类</p>
 * <p>Table: tb_item - 商品表</p>
 *
 * @since 2017-09-21 08:35:09
 */
public class Item {

    /** id - 商品id，同时也是商品编号 */
    private Long id;

    /** title - 商品标题 */
    private String title;

    /** sell_point - 商品卖点 */
    private String sellPoint;

    /** price - 商品价格，单位为：分 */
    private Long price;

    /** num - 库存数量 */
    private Integer num;

    /** barcode - 商品条形码 */
    private String barcode;

    /** image - 商品图片 */
    private String image;

    /** cid - 所属类目，叶子类目 */
    private Long cid;

    /** status - 商品状态，1-正常，2-下架，3-删除 */
    private Byte status;

    /** created - 创建时间 */
    private Date created;

    /** updated - 更新时间 */
    private Date updated;


    public Long getId(){
        return this.id;
    }
    public void setId(Long id){
        this.id = id;
    }

    public String getTitle(){
        return this.title;
    }
    public void setTitle(String title){
        this.title = title;
    }

    public String getSellPoint(){
        return this.sellPoint;
    }
    public void setSellPoint(String sellPoint){
        this.sellPoint = sellPoint;
    }

    public Long getPrice(){
        return this.price;
    }
    public void setPrice(Long price){
        this.price = price;
    }

    public Integer getNum(){
        return this.num;
    }
    public void setNum(Integer num){
        this.num = num;
    }

    public String getBarcode(){
        return this.barcode;
    }
    public void setBarcode(String barcode){
        this.barcode = barcode;
    }

    public String getImage(){
        return this.image;
    }
    public void setImage(String image){
        this.image = image;
    }

    public Long getCid(){
        return this.cid;
    }
    public void setCid(Long cid){
        this.cid = cid;
    }

    public Byte getStatus(){
        return this.status;
    }
    public void setStatus(Byte status){
        this.status = status;
    }

    public Date getCreated(){
        return this.created;
    }
    public void setCreated(Date created){
        this.created = created;
    }

    public Date getUpdated(){
        return this.updated;
    }
    public void setUpdated(Date updated){
        this.updated = updated;
    }
}